locale: en-US
title: Bohong (Lucia) Liu
name: Bohong (Lucia) Liu
description: Undergraduate researcher in computational political science, text-as-data, quantitative methods, and political economy.
url: https://94007369.github.io
baseurl: ""
repository: 94007369/94007369.github.io
author:
  name: Bohong (Lucia) Liu
  email: 23300160032@m.fudan.edu.cn
  github: "94007369"
include: [_pages]
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - docker-compose.yaml
  - package.json
  - package-lock.json
  - node_modules
  - vendor
  - markdown_generator
  - talkmap
  - talkmap.py
  - talkmap.ipynb
  - _posts
  - _publications
  - _talks
  - _teaching
  - _portfolio
  - files
  - scripts
  - tests
  - .github
  - talkmap_out.ipynb
  - _pages/archive-layout-with-content.md
  - _pages/category-archive.html
  - _pages/collection-archive.html
  - _pages/cv-json.md
  - _pages/markdown.md
  - _pages/non-menu-page.md
  - _pages/page-archive.html
  - _pages/portfolio.html
  - _pages/publications.html
  - _pages/sitemap.md
  - _pages/tag-archive.html
  - _pages/talkmap.html
  - _pages/talks.html
  - _pages/teaching.html
  - _pages/terms.md
  - _pages/year-archive.html
markdown: kramdown
highlighter: rouge
permalink: /:title/
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: academic
timezone: America/Los_Angeles
